from . import document
from . import document_tag
from . import document_access
from . import document_mixin
from . import document_sharing
from . import document_operation
from . import document_request_wizard
from . import document_link_wizard
from . import document_delete_wizard
from . import res_config_settings
